import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import { Logo, Car, BLEConnect, BLEDisconnect, HomeCommand, WorkCommand, SolarCommand, OutageCommand } from '../icons';
import { motion } from 'framer-motion';
import ReactModal from 'react-modal';

const Home = () => {
  const [isConnected, setIsConnected] = useState(false);
  const [paired_devices, setDevices] = useState([]);
  const [characteristicCache, setCharacteristic] = useState(null);
  const [receivedData, setReceived] = useState(null);
  const [receiveModal, setModal] = useState(false);
  const [deviceCache, setDevice] = useState(null);

  const serviceUUID = 0xFFE0;
  const charUUID = 0xFFE1;

  const pairCar = (device) => {
    if (device.gatt.connected && characteristicCache) {
      console.log("Already Connected.");
      return;
    }

    device.gatt.connect().then(
      server => {
        setDevice(device);
        setIsConnected(true);
        console.log("GATT Server connected, finding service...");
        return server.getPrimaryService(serviceUUID);
      }
    ).then(
      service => {
        console.log("Found service, finding characteristic...");
        return service.getCharacteristic(charUUID);
      }
    ).then(
      characteristic => {
        console.log("Found characteristic, starting notifications...");
        setCharacteristic(characteristic);
        return characteristic.startNotifications();
      }
    ).then(characteristic => {
      console.log(characteristic, "Notifications started.");
      characteristic.addEventListener('characteristicvaluechanged',
        handleCharacteristicValueChanged);
    }
    )
  }

  function handleCharacteristicValueChanged(event) {
    let value = new TextDecoder().decode(event.target.value);
    setReceived(value);
    setModal(true);
    console.log(value, 'in');
  }
  function disconnect() {
    if (deviceCache) {
      console.log('Disconnecting from "' + deviceCache.name + '" bluetooth device...');

      if (deviceCache.gatt.connected) {
        deviceCache.gatt.disconnect();
        console.log('"' + deviceCache.name + '" bluetooth device disconnected');
      }
      else {
        console.log('"' + deviceCache.name +
          '" bluetooth device is already disconnected');
      }
    }

    if (characteristicCache) {
      characteristicCache.removeEventListener('characteristicvaluechanged',
        handleCharacteristicValueChanged);
      setCharacteristic(null);
    }


    setDevice(null);
    setIsConnected(false);
    setDevices([]);
  }

  const sendCommand = (data) => {
    data = String(data);

    if (!data || !characteristicCache) {
      return;
    }

    data += '\n';

    if (data.length > 20) {
      let chunks = data.match(/(.|[\r\n]){1,20}/g);

      writeToCharacteristic(characteristicCache, chunks[0]);

      for (let i = 1; i < chunks.length; i++) {
        setTimeout(() => {
          writeToCharacteristic(characteristicCache, chunks[i]);
        }, i * 100);
      }
    }
    else {
      characteristicCache.writeValue(new TextEncoder().encode(data))
    }
  }

  function getDevicesOnClick() {
    console.log('Getting existing permitted Bluetooth devices...');

    navigator.bluetooth.getDevices()
      .then(devices => {
        console.log('> Got ' + devices.length + ' Bluetooth devices.');
        for (const device of devices) {
          console.log('  > ' + device.name + ' (' + device.id + ')');
        }
        setDevices(devices)
      })
      .catch(error => {
        console.log('Argh! ' + error);
      });
  }

  function requestDeviceOnClick() {
    console.log('Requesting any Bluetooth device...');
    navigator.bluetooth.requestDevice({
      filters: [{ services: [serviceUUID] }]
    })
      .then(device => {
        console.log('> Requested ' + device.name + ' (' + device.id + ')');
      }).catch(error => {
        console.log('Argh! ' + error);
      });
  }

  const closeModal = () => {
    setModal(false);
  };


  return (
    <HomeWrap>
      <Head>
        <title>EVEE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#000" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/icon-192x192.png" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
      </Head>
      <HomeHeader>
        <motion.div whileTap={{ scale: 1.2 }} whileHover={{ scale: 1.1 }}>
          {!isConnected ? <BLEConnectIcon onClick={() => { requestDeviceOnClick(); }} />
            : <BLEDisconnectIcon onClick={() => { disconnect(); }} />}
        </motion.div>
      </HomeHeader>

        <Button onClick={() => { getDevicesOnClick(); }} />

      {!isConnected && paired_devices.map((car, i) => {
        return (
          <motion.div key={car.name} whileTap={{ scale: 1.2 }} whileHover={{ scale: 1.1 }}>
            <CarSelect carColor={colors[i]} onClick={() => { pairCar(car); }} />
            {car.name}
          </motion.div>
        )
      })}

      {isConnected &&
        <>
            <SendHome onClick={() => { sendCommand('h'); }} />
            <SendWork onClick={() => { sendCommand('w'); }} />
            <SendSolar onClick={() => { sendCommand('s'); }} />
            <SendOutage onClick={() => { sendCommand('o'); }} />
        </>
      }

      <ReactModal
        isOpen={receiveModal}
        onRequestClose={closeModal}
        ariaHideApp={false}
        contentLabel="Selected Option"
        style={{
          overlay: {
            backgroundColor: 'rgba(0,0,0,0.3)'
          },
          content: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: 'white',
            border: 'none',
            borderRadius: '1em',
            height: '60vh',
            width: '80vh',
            left: '50%',
            top: '50%',
            right: '0',
            bottom: '0',
            transform: 'translate(-50%, -50%)'
          }
        }
        }
      >
        Received Data: {receivedData}
      </ReactModal>

    </HomeWrap>
  )
}

const HomeWrap = styled.div`
  height: 100vh;
  display: flex;
  margin: 0;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: #000;
`;

const HomeHeader = styled.div`
  position: absolute;
  left: 0;
  top: 2vh;
`

const Button = styled(Logo)`
  position: absolute;
  height: 30vh;
  width: 30vh;
  border-radius: 50%;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  text-align: center;
  transition: transform .2s;
  &:hover, &:active{
    transform: scale(1.05);
  }
`;


const CarSelect = styled(Car)`
  height: 20vh;
  path {fill: ${({ carColor }) => carColor ? carColor : 'white'};}
`;

const BLEConnectIcon = styled(BLEConnect)`
  width: 60px;
`;

const BLEDisconnectIcon = styled(BLEDisconnect)`
  width: 40px;
  padding: 10px;
`;

const SendHome = styled(HomeCommand)`
  position: absolute;
  height: 10vh;
  width: 10vh;
  border-radius: 50%;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  transition: transform .2s;
  transform: translateY(-25vh);
  &:hover, &:active{
    transform: scale(1.05) translateY(-25vh);
  }
`;

const SendWork = styled(WorkCommand)`
  position: absolute;
  height: 10vh;
  width: 10vh;
  border-radius: 50%;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  transition: transform .2s;
  transform: translateY(25vh);
  &:hover, &:active{
    transform: scale(1.05) translateY(25vh);
  }
`;

const SendSolar = styled(SolarCommand)`
  position: absolute;
  height: 10vh;
  width: 10vh;
  border-radius: 50%;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  transition: transform .2s;
  transform: translateX(25vh);
  &:hover, &:active{
    transform: scale(1.05) translateX(25vh);
  }
`;

const SendOutage = styled(OutageCommand)`
  position: absolute;
  height: 10vh;
  width: 10vh;
  border-radius: 50%;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  transition: transform .2s;
  transform: translateX(-25vh);
  &:hover, &:active{
    transform: scale(1.05) translateX(-25vh);
  }
`;


const colors = ['red', 'blue', 'green', 'purple'];



export default Home;